ForMenu/ForMenu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public.urls')),
    path('manager/', include('manager.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

ForMenu/manager/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.dashboard, name='dashboard-manager'),
    path('crear/menu/', views.crearMenu, name='crearMenu'),
    path('completar/perfil/', views.completarPerfil, name='completarPerfil'),
    path('ajustes/perfil/', views.ajustes, name='ajustes'),
    path('ajustes/password/', views.password, name='password'),
    path('eliminar/menu/<str:id>', views.eliminarMenu, name='eliminarMenu'),
    path('modificar/menu/<str:id>', views.modificarMenu, name='modificarMenu'),
    path('modificar/imagen/', views.modificarImagen, name='modificarImagen'),
    path('modificar/datos/publicos/', views.modificarDatosPublicos, name='modificarDatosPublicos'),
    path('modificar/direccion/', views.modificarDireccion, name='modificarDireccion'),
    path('modificar/horario/', views.modificarHorario, name='modificarHorario'),
]

ForMenu/manager/models.py
# django
from django.db import models
from django.contrib.auth.models import User
# utils
from PIL import Image


class Restaurante(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField( 'restaurant name', max_length=200,)
    telefono = models.CharField( max_length=17, blank=True, )
    ciudad = models.CharField('Ciudad',max_length=50,default='Alicante')
    pais = models.CharField('País',max_length=50,default='España')
    provincia = models.CharField('Provincia',max_length=50,default='Alicante')
    direccion = models.CharField( 'Dirección', max_length=200, default='Calle España')
    imagen = models.ImageField(upload_to='perfil', blank=True, null=True)
    is_active = models.BooleanField('active',default=True)
    is_complete = models.BooleanField('complete restaurant',default=False)
    created = models.DateTimeField('created at',auto_now_add=True,help_text='Date time on which the object was created')
    modified = models.DateTimeField('Modified at',auto_now=True,help_text='Date time on which the object was last modified')

    def save(self, force_insert=False, force_update=False, using=None):
        super().save()
        if self.imagen:
            img = Image.open(self.imagen.path)
            if img.height > 1500 or img.width > 1500:
                output_size = (1500, 1500)
                img.thumbnail((output_size), Image.ANTIALIAS)
                img.save(self.imagen.path)

    def __str__(self):
        return self.nombre




class Horario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    lunes = models.BooleanField(default=True)
    lunesTurno = models.BooleanField(default=False)
    lunesOpen = models.CharField(max_length=5, default="08:00")
    lunesClose = models.CharField(max_length=5, default="13:00")
    lunesOpen2 = models.CharField(max_length=5, default="15:00")
    lunesClose2 = models.CharField(max_length=5, default="20:00")

    martes = models.BooleanField(default=True)
    martesTurno = models.BooleanField(default=False)
    martesOpen = models.CharField(max_length=5, default="08:00")
    martesClose = models.CharField(max_length=5, default="13:00")
    martesOpen2 = models.CharField(max_length=5, default="15:00")
    martesClose2 = models.CharField(max_length=5, default="20:00")

    miercoles = models.BooleanField(default=True)
    miercolesTurno = models.BooleanField(default=False)
    miercolesOpen = models.CharField(max_length=5, default="08:00")
    miercolesClose = models.CharField(max_length=5, default="13:00")
    miercolesOpen2 = models.CharField(max_length=5, default="15:00")
    miercolesClose2 = models.CharField(max_length=5, default="20:00")

    jueves = models.BooleanField(default=True)
    juevesTurno = models.BooleanField(default=False)
    juevesOpen = models.CharField(max_length=5, default="08:00")
    juevesClose = models.CharField(max_length=5, default="13:00")
    juevesOpen2 = models.CharField(max_length=5, default="15:00")
    juevesClose2 = models.CharField(max_length=5, default="20:00")

    viernes = models.BooleanField(default=True)
    viernesTurno = models.BooleanField(default=False)
    viernesOpen = models.CharField(max_length=5, default="08:00")
    viernesClose = models.CharField(max_length=5, default="13:00")
    viernesOpen2 = models.CharField(max_length=5, default="15:00")
    viernesClose2 = models.CharField(max_length=5, default="20:00")

    sabado = models.BooleanField(default=True)
    sabadoTurno = models.BooleanField(default=False)
    sabadoOpen = models.CharField(max_length=5, default="08:00")
    sabadoClose = models.CharField(max_length=5, default="13:00")
    sabadoOpen2 = models.CharField(max_length=5, default="15:00")
    sabadoClose2 = models.CharField(max_length=5, default="20:00")

    domingo = models.BooleanField(default=True)
    domingoTurno = models.BooleanField(default=False)
    domingoOpen = models.CharField(max_length=5, default="08:00")
    domingoClose = models.CharField(max_length=5, default="13:00")
    domingoOpen2 = models.CharField(max_length=5, default="15:00")
    domingoClose2 = models.CharField(max_length=5, default="20:00")

    created = models.DateTimeField( 'created at', auto_now_add=True, help_text='Date time on which the object was created')
    modified = models.DateTimeField('Modified at',auto_now=True,help_text='Date time on which the object was last modified')

    def __str__(self):
        return self.user.username





class Menu(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    qr = models.ImageField(upload_to='QR')
    pdf = models.FileField(upload_to='PDF')
    created = models.DateTimeField('created at',auto_now_add=True,help_text='Date time on which the object was created')
    modified = models.DateTimeField('Modified at',auto_now=True,help_text='Date time on which the object was last modified')
    def __str__(self):
        return self.nombre

ForMenu/manager/forms.py
from django import forms
from django.contrib.auth.models import User
from manager.models import Menu, Horario, Restaurante


class menuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = (
            'nombre',
            'pdf',
        )

class userForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name'
        )



class ajustesForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username'
        )

class emailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
        )


class restauranteForm(forms.ModelForm):
    class Meta:
        model = Restaurante
        fields = (
            'nombre',
            'telefono',
        )


class direccionForm(forms.ModelForm):
    class Meta:
        model = Restaurante
        fields = (
            'direccion',
            'ciudad',
            'provincia',
            'pais'
        )


class horarioForm(forms.ModelForm):
    class Meta:
        model = Horario
        fields = (
            'lunes',
            'lunesTurno',
            'lunesOpen',
            'lunesClose',
            'lunesOpen2',
            'lunesClose2',
            'martes',
            'martesTurno',
            'martesOpen',
            'martesClose',
            'martesOpen2',
            'martesClose2',
            'miercoles',
            'miercolesTurno',
            'miercolesOpen',
            'miercolesClose',
            'miercolesOpen2',
            'miercolesClose2',
            'jueves',
            'juevesTurno',
            'juevesOpen',
            'juevesClose',
            'juevesOpen2',
            'juevesClose2',
            'viernes',
            'viernesTurno',
            'viernesOpen',
            'viernesClose',
            'viernesOpen2',
            'viernesClose2',
            'sabado',
            'sabadoTurno',
            'sabadoOpen',
            'sabadoClose',
            'sabadoOpen2',
            'sabadoClose2',
            'domingo',
            'domingoTurno',
            'domingoOpen',
            'domingoClose',
            'domingoOpen2',
            'domingoClose2',
        )

ForMenu/manager/views/dashboard.py
# django
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.hashers import check_password
# models
from manager.models import Restaurante, Horario, Menu
# forms
from manager.forms import menuForm, emailForm, restauranteForm, direccionForm, horarioForm, userForm, ajustesForm
# utils
import qrcode
from unidecode import unidecode





@login_required
def dashboard(request):
    # pantalla principal donde se muestra todo lo que puede hacer un
    # cliente registrado
    if request.user.is_superuser:
        return redirect('/admin')

    restaurante = Restaurante.objects.get(user=request.user)
    horario = Horario.objects.get(user=request.user)
    menus = Menu.objects.filter(user=request.user)
    context = {
        'restaurante': restaurante,
        'horario': horario,
        'menus': menus,
    }

    return render(request, 'manager/dashboard.html', context)
    
    
    
    

@login_required
def crearMenu(request):
    # función que permite crear menús y generar el QR único que estos tendrás
    if request.method == 'POST':
        form = menuForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                menu = form.save(commit=False)
                menu.user = request.user
                menu.save()
                # generamos el QR una vez el pdf esté guardado para que no de errores
                img = qrcode.make('https://www.4menu.es/descargar/' + str(menu.id))
                img.save(settings.MEDIA_ROOT + '/QR/' + menu.user.username + '_' + str(menu.id) + '.png')
                # lo asignamos al menú que acabamos de crear antes
                menu.qr = 'QR/' + menu.user.username + '_' + str(menu.id) + '.png'
                menu.save()
                messages.success(request, f'Tu menú ha sido creado correctamente')
            except:
                # no se ha logrado crear el qr por lo que eliminamos todo para que no de fallo
                menu.delete()
                messages.error(request, f'Ha habido un error, prueba de nuevo')
        else:
            messages.error(request, f'Ha habido un error, prueba de nuevo')
    return redirect('dashboard-manager')





@login_required
def modificarMenu(request, id):
    # función que nos permite cambiar el archivo y nombre de un Menú
    menu = Menu.objects.get(id=id)

    if request.user == menu.user:
        if request.method == 'POST':
            form = menuForm(request.POST, request.FILES, instance=menu)
            if form.is_valid():
                menu = form.save()
                menu.save()
                messages.success(request, f'¡Enhorabuena! Tu menú ha sido modificado correctamente')
        else:
            messages.error(request, f'Ha habido un error, prueba de nuevo')
    else:
        messages.error(request, f'No puedes modificar menús que no son tuyos')

    return redirect('dashboard-manager')





@login_required
def eliminarMenu(request, id):
    # función que nos permite eliminar un menú 
    menu = Menu.objects.get(id=id)

    if request.user == menu.user:
        if menu.delete():
            messages.success(request, f'Menú eliminado correctamente')
        else:
            messages.error(
                request, f'Ha habido un error, prueba de nuevo')
    else:
        messages.error(request, f'No puedes eliminar menús que no son tuyos')

    return redirect('dashboard-manager')






@login_required
def modificarImagen(request):
    # función que modifica la imagen de perfil de un restaurante
    if request.method == 'POST':
        restaurante = Restaurante.objects.get(user=request.user)
        restaurante.imagen = request.FILES['imagen']
        restaurante.save()
        messages.success(request, f'Imagen modificada correctamente')
    return redirect('dashboard-manager')





@login_required
def modificarDatosPublicos(request):
    # función que nos permite modificar los datos publicos
    # de un restaurante
    if request.method == 'POST':
        restaurante = Restaurante.objects.get(user=request.user)

        e_form = emailForm(request.POST, instance=request.user)
        r_form = restauranteForm(request.POST, instance=restaurante)

        if e_form.is_valid() and r_form.is_valid():
            e_form.save()
            r_form.save()
            messages.success(
                request, f'¡Tus datos públicos han sido actualizados!')
        else:
            messages.error(
                request, f'Ha habido un error, prueba de nuevo')
    return redirect('dashboard-manager')





@login_required
def modificarDireccion(request):
    # función que nos permite modificar la dirección de un restaurante
    if request.method == 'POST':
        restaurante = Restaurante.objects.get(user=request.user)
        form = direccionForm(request.POST, instance=restaurante)
        if form.is_valid():
            form.save()
            messages.success(
                request, f'¡Tu dirección ha sido modificada!')
        else:
            messages.error(
                request, f'Ha habido un error, prueba de nuevo')
    return redirect('dashboard-manager')





@login_required
def modificarHorario(request):
    # función que nos permite modificar el horario de un restaurante
    if request.method == 'POST':
        horario = Horario.objects.get(user=request.user)

        form = horarioForm(request.POST, instance=horario)

        if form.is_valid():
            form.save()
            messages.success(request, f'¡Tu horario ha sido modificado!')
        else:
            messages.error(
                request, f'Ha habido un error, prueba de nuevo')
    return redirect('dashboard-manager')





@login_required
def completarPerfil(request):
    # función que nos ayuda a que cuando un restaurante se acaba de
    # registrar termine de registrar y rellenar los datos de su perfil
    # para que no hallan errores ni campos vacios
    if request.method == 'POST':
        horario = Horario.objects.get(user=request.user)
        restaurante = Restaurante.objects.get(user=request.user)

        u_form = userForm(request.POST, instance = request.user)
        h_form = horarioForm(request.POST, instance=horario)
        r_form = direccionForm(request.POST, instance=restaurante)

        if h_form.is_valid() and r_form.is_valid() and u_form.is_valid():
            h_form.save()
            r_form.save()
            u_form.save()
            restaurante.is_complete = True
            restaurante.save()

            messages.success(request, f'¡Tu cuenta ha sido completada!')
        else:
            messages.error(
                request, f'No se ha podido completar tu cuenta')
    return redirect('dashboard-manager')





@login_required
def ajustes(request):
    # función que nos permite modificar los datos personales de un restaurante
    if request.method == 'POST':
        form = ajustesForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'¡Tus datos han sido actualizados!')
        else:
            messages.error(
                request, f'Ha habido un error, prueba de nuevo')
    return redirect('dashboard-manager')





@login_required
def password(request):
    # función que nos permite modificar la contraseña de un restaurante
    if request.method == 'POST':
        if check_password(request.POST['passwordOld'], request.user.password):
            if request.POST['password'] == request.POST['password2']:
                request.user.set_password(request.POST['password'])
                request.user.save()
                messages.success(
                    request, f'Tu contraseña ha sido modificada, por favor vuelve a iniciar sesión')
            else:
                messages.error(
                    request, f'Las contraseñas no coinciden')
        else:
            messages.error(
                    request, f'La contraseña anterior es incorrecta')
    return redirect('dashboard-manager')

ForMenu/manager/templates/manager/ajustes.html
<div class="lateralDiv px-md-5 pt-md-5 p-3" id="ajustesDiv">
    <span class="icon-cross" id="closeAjustes"></span>
    <form method="post" action="{% url 'ajustes'%}">{% csrf_token %}
        <div class="row m-0 pt-5 pb-5">
            <div class="col-md-8 offset-md-2 p-0">
                 <p class="tituloResultado mb-3 pb-3 border-bottom text-left">
                    Ajustes de @{{user.username}}
                </p>
            </div>
            <div class="col-md-8 offset-md-2 p-0">
                <small class="text-muted">Nombre de usuario</small>
                <input type="text" class="inputLocal mb-3" required name="username" value="{{ user.username }}">
                <small class="text-muted">Nombre</small>
                <input type="text" class="inputLocal mb-3" required name="first_name" value="{{ user.first_name }}">
                <small class="text-muted">Apellidos</small>
                <input type="text" class="inputLocal" required name="last_name" value="{{ user.last_name }}">
                <button class="btn btn-sm btn-primary py-2 px-3 mt-4 float-right" style="border-radius: 25px" type="submit">Guardar cambios</button>
                <button class="btn btn-sm btn-dark py-2 px-3 mt-4 float-left mr-3" style="border-radius: 25px" type="button" data-toggle="modal" data-target="#contraseña">contraseña</button>
            </div>
        </div>
    </form>
</div> 


<!-- Modal -->
<div class="modal fade" id="contraseña" tabindex="-1" role="dialog" aria-labelledby="contraseña" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content p-5">  
            <form method="post" action="{% url 'password' %}">{% csrf_token %}
                <div class="row m-0">
                    <div class="col-12 p-0">
                        <p class="tituloResultado mb-3 pb-3 border-bottom text-left">
                            Modificar contraseña
                        </p>
                    </div>
                    <div class="col-12 p-0">
                        <small class="text-muted">Contraseña antigua</small>
                        <input type="password" class="inputLocal mb-3" required name="passwordOld">
                        <small class="text-muted">Contraseña nueva</small>
                        <input type="password" class="inputLocal mb-3" required name="password">
                        <small class="text-muted">Contraseña nueva (confirmación)</small>
                        <input type="password" class="inputLocal" required name="password2">
                    </div>
                    <div class="col-12 p-0">
                        <button class="btn btn-sm btn-primary py-2 px-3 mt-3 float-right" style="border-radius: 25px" type="submit">Modificar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

ForMenu/manager/templates/manager/dashboard.html
{% extends "public/base.html" %}
{% load static %}

{% block title %}
    Manager de {{ restaurante.nombre}}
{% endblock %}

{% block content %} 
<style>
    body{
        background-color: #f4f7f8
    }
</style>

    {% if not restaurante.is_complete %}
        {% include 'manager/completar.html'%}
    {% endif %}

   	<div style="width: 100%; margin-top: 70px">
        {% if restaurante.imagen %} 
            <div class="portadaLocal" id="bluh"  style="background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.3) 50%, rgba(0, 0, 0, 0.7) 100%), url({{restaurante.imagen.url}}) no-repeat;background-size: cover; background-position: center !important;">
        {% else %}
            <div class="portadaLocal" id="bluh"  style="background: #424242"> 
            <div class="alert alert-warning alertaImagen shadow-sm mb-0" role="alert">
                😭 Vaya, al parecer no tienes una imagen de perfil, deberías subir una para que tus clientes te reconozcan mejor.
            </div>            
        {% endif %}
                
                <form method="post" enctype="multipart/form-data" id="cambiarFoto"action="{% url 'modificarImagen' %}">{% csrf_token %}
                    <div class="contenedor p-3">
                        <p class="tituloLocal">
                            {{restaurante.nombre}}
                        </p>
                        <label class="inputCambiarFondo">
                            <input  type="file" name="imagen" required accept="image/*" class="clearablefileinput shadowHover" id="id_imagen" value="{% if restaurante.imagen%} {{restaurante.imagen}} {% endif %} ">
                            <a class="btn btn-primary mr-2 shadowHover" role="button" href="#">
                                <span class="icon-camera"></span>
                            </a>
                        </label>
                        <button class="btn btn-primary botonNuevaImagen shadow py-2 px-3" type="submit">Guardar cambios</button>

                        <!-- progress bar -->
                        <div class="progress" id="progressBarFotoDiv">
                            <div class="progress-bar" id="progressBarFoto" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <!-- end progress bar -->
                    </div>
                </form>
            </div> 



		<div class="contenedor px-3 pb-5">
            <div class="row m-0">
                <div class="col-12 p-0 desaparecer5">
                    {% if restaurante.is_complete %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert shadow-sm mb-0 mt-4 alert-{{ message.tags }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                </div>


                <div class="col-md-8 p-0 pr-md-4">
                    <div class="row m-0 ">
                        <div class="col-12 bg-white shadow-sm rounded p-md-4 p-3 mt-4">
                            <div class="row m-0">
                                <div class="col-12 p-0 mb-4">
                                    <div class="alert mb-0 alert-primary">
                                        <p class="mb-0 pr-1">
                                            Si modificas tu menú el QR no 
                                            cambiará y no necesitarás imprimirlo de nuevo. 😎
                                        </p>
                                    </div>
                                </div>
                                <div class="col-12 px-0 mb-3 border-bottom pb-3">
                                    <div class="tituloMenuLocal">
                                        Menús disponibles
                                    </div>   
                                </div>
                                {% include 'manager/menu.html' %}
                                <div class="col-12 p-0 mt-3 pt-3 border-top text-center">
                                    <a class="btn btn-sm px-4 py-3 btn-transparent shadowHover" role="button" id="activeCrearMenu" style="border-radius:30px">
                                        <span class="icon-plus mr-2"></span> Añadir nuevo menú
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 p-0 mt-4">
                            <form method="post" action="{% url 'modificarDatosPublicos' %}">{% csrf_token %}
                                <div class="row m-0 ">
                                    <div class="col-12 p-0  bg-white shadow-sm rounded p-4">
                                        <div class="tituloSecundarioLocal mb-3 pb-3 border-bottom">
                                            Datos públicos
                                        </div> 
                                        <small class="text-muted">Nombre del local</small>
                                        <input type="text" class="inputLocal mb-3" required name="nombre" value="{{ restaurante.nombre }}">
                                        <small class="text-muted">Teléfono</small>
                                        <input type="number" class="inputLocal mb-3" required name="telefono" value="{{ restaurante.telefono }}">
                                        <small class="text-muted">Correo electrónico</small>
                                        <input type="email" class="inputLocal" required name="email" value="{{ user.email }}">
                                        <button class="btn btn-sm btn-primary py-2 px-3 mt-3 float-right" style="border-radius: 25px" type="submit">Guardar cambios</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6 p-0 pl-md-4 mt-4">
                            <form method="post" action="{% url 'modificarDireccion' %}">{% csrf_token %}
                                <div class="row m-0 ">
                                    <div class="col-12 p-0  bg-white shadow-sm rounded  p-4 ">
                                        <div class="tituloSecundarioLocal mb-3 pb-3 border-bottom">
                                            Dirección
                                        </div> 
                                        <p class="mb-0">
                                            <small class="text-muted">Dirección</small>
                                            <input type="text" class="inputLocal mb-3" required name="direccion" value="{{ restaurante.direccion }}">
                                            <small class="text-muted">Ciudad</small>
                                            <input type="text" class="inputLocal mb-3" required name="ciudad" value="{{ restaurante.ciudad }}">
                                             <small class="text-muted">Provincia</small>
                                            <input type="text" class="inputLocal mb-3" required name="provincia" value="{{ restaurante.provincia }}">
                                            <small class="text-muted">Pais</small>
                                            <input type="text" class="inputLocal" required name="pais" value="{{ restaurante.pais }}">
                                            <button class="btn btn-sm btn-primary py-2 px-3 mt-3 float-right" type="submit"style="border-radius: 25px">Guardar cambios</button>
                                        </p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div> 

                <div class="col-md-4 p-0">
                    <div class="row m-0">
                        <div class="col-12 p-0  bg-white  shadow-sm rounded p-4 mt-4">
                            <div class="tituloSecundarioLocal mb-0 pb-3 border-bottom">  
                                Horario
                            </div> 
                            <form method="post" action="{% url 'modificarHorario' %}">{% csrf_token %}
                                <div class="row m-0">
                                    {% include 'manager/horario.html' %} 
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
{% endblock %}